-- global.lua
-- Author: cndy1860
-- Date: 2018-11-19
-- function: 全局变量相关操作


------PAGE LIST------
PAGE_NONE = "PAGE_NONE"		--未定义界面
PAGE_MAIN = "PAGE_MAIN"
PAGE_MAIN_MATCH = "PAGE_MAIN_MATCH"
PAGE_MAIN_CLUB = "PAGE_MAIN_CLUB"
PAGE_MAIN_CONCTRACT = "PAGE_MAIN_CONCTRACT"
PAGE_MAIN_EXTRAS = "PAGE_MAIN_EXTRAS"
PAGE_ONLINE_MATCH = "PAGE_ONLINE_MATCH"
PAGE_COACH_RANK = "PAGE_COACH_RANK"
PAGE_MATCHED = "PAGE_MATCHED"
PAGE_ROSTER = "PAGE_ROSTER"
PAGE_PLAYING = "PAGE_PLAYING"
PAGE_END_READY = "PAGE_END_READY"
PAGE_INTERVAL = "PAGE_INTERVAL"
PAGE_INTERVAL_READY = "PAGE_INTERVAL_READY"
PAGE_RANK_UP = "PAGE_RANK_UP"

------ERR CODE------
ERR_MAIN = "ERR_MAIN"  		--主函数错误
ERR_NORMAL = "ERR_NORMAL"
ERR_FILE = "ERR_FILE"
ERR_PARAM = "ERR_PARAM"
ERR_TIMEOUT = "ERR_TIMEOUT"
ERR_WARNING = "ERR_WARNING"
ERR_UNKOWN = "ERR_UNKOWN"


------TASK------
TASK_NONE = "TASK_NONE"
TASK_BREAK_POINT = "TASK_BREAK_POINT"
TASK_SIM = "TASK_SIM"

------PROCESS------
PROCESS_NONE = "PROCESS_NONE"


------STATUS------
IS_RESTARTED_SCRIPT = false



------API------
sleep = mSleep